default:
  webhook:
    polling: yes

    # If polling: no
    url: "https://server.tld:8443/secret-path" # Must be an https address
    path: "/secret-path"
    port: 5000
    ssl:
      enabled: no # Disabled if the Node.js app is behind a proxy that does SSL offloading
      key: "server-key.pem"
      cert: "server-cert.pem"
      ca: "ca.pem"

  products:
    - "BTC-USD"
    - "BCH-USD"
    - "ETH-USD"
    - "LTC-USD"
  aliases:
    BTC-USD:
      - "bitcoin"
    ETH-USD:
      - "ethereum"
      - "ether"
    LTC-USD:
      - "litecoin"
  defaultCurrency: "USD"
  currencySymbols:
    USD: "$"
    EUR: "€"
    GBP: "£"
    BTC: "Ƀ"
    BCH: "Ƀ"
    ETH: "Ξ"
    LTC: "Ł"

  telegram:
    # Pass this secret as environmental variable
    botToken: null

  gdax:
    apiUri: "https://api.gdax.com"
    wsUri: "wss://ws-feed.gdax.com"

prod:
  usePolling: no

# Hostname-to-environment dictionary
hostnames:
  dev:
    - "*.local"
