default:
  webhook:
    polling: yes

    # If polling: no
    url: "https://server.tld:8443/secret-path" # Must be an https address
    path: "/secret-path"
    port: 3000
    ssl:
      enabled: no # Disabled if the Node.js app is behind a proxy that does SSL offloading
      key: "server-key.pem"
      cert: "server-cert.pem"
      ca: "ca.pem"

  mongodbUrl: "mongodb://localhost/TheCoinsBot"

  products:
    - "BTC-USD"
    - "BTC-EUR"
    - "BTC-GBP"
    - "BCH-USD"
    - "ETH-USD"
    - "ETH-BTC"
    - "ETH-EUR"
    - "LTC-USD"
    - "LTC-BTC"
    - "LTC-EUR"
  aliases:
    BTC:
      - "bitcoin(s?)"
    ETH:
      - "ethereum(s?)"
      - "ether(s?)"
    LTC:
      - "litecoin(s?)"
  decimalDigits:
    # All other products have 2 digits
    "ETH-BTC": 5
    "LTC-BTC": 5
  # https://support.gdax.com/customer/en/portal/articles/2425188-which-countries-and-states-can-access-gdax-
  regions:
    AU:
      label: "üá¶üá∫ Australia"
      # AU can trade ETH-BTC and LTC-BTC only, but showing USD prices too for reference
      products: ["ETH-BTC", "LTC-BTC", "BTC-USD", "BCH-USD", "ETH-USD", "LTC-USD"]
      fiat: "USD"
    CA:
      label: "üá®üá¶ Canada"
      # CA can trade ETH-BTC and LTC-BTC only, but showing USD prices too for reference
      products: ["ETH-BTC", "LTC-BTC", "BTC-USD", "BCH-USD", "ETH-USD", "LTC-USD"]
      fiat: "USD"
    EU:
      label: "üá™üá∫ Europe"
      products: ["BTC-EUR", "ETH-EUR", "LTC-EUR", "ETH-BTC", "LTC-BTC"]
      fiat: "EUR"
    SG:
      label: "üá∏üá¨ Singapore"
      # SG can trade ETH-BTC and LTC-BTC only, but showing USD prices too for reference
      products: ["ETH-BTC", "LTC-BTC", "BTC-USD", "BCH-USD", "ETH-USD", "LTC-USD"]
      fiat: "USD"
    US:
      label: "üá∫üá∏ USA"
      products: ["BTC-USD", "BCH-USD", "ETH-USD", "LTC-USD", "ETH-BTC", "LTC-BTC"]
      fiat: "USD"
    UK:
      label: "üá¨üáß United Kingdom"
      products: ["BTC-GBP", "BTC-EUR", "ETH-EUR", "LTC-EUR", "ETH-BTC", "LTC-BTC"]
      fiat: ["GBP", "EUR"]
    ZZ:
      label: "üåç Rest of World"
      # Show USD prices for ROW
      products: ["BTC-USD", "BCH-USD", "ETH-USD", "LTC-USD", "ETH-BTC", "LTC-BTC"]
      fiat: "USD"
  # For users that do not have a region set (for some reason)
  defaultRegion: "ZZ"
  currencySymbols:
    USD: "$"
    EUR: "‚Ç¨"
    GBP: "¬£"
    BTC: "…É"
    BCH: "…É"
    ETH: "Œû"
    LTC: "≈Å"

  telegram:
    # Pass this secret as environmental variable
    botToken: null

  gdax:
    apiUri: "https://api.gdax.com"
    wsUri: "wss://ws-feed.gdax.com"

production:
  webhook:
    polling: no

# Hostname-to-environment dictionary
hostnames:
  dev:
    - "*.local"
